### ISSUE TITLE
Unable to install on Windows with MSYS2

### ISSUE THREAD

**Issue by OTLabs** [apache/mynewt-core#1580]
I have hard time getting to run newt 1.5.0 on Windows. I run "newt new test" without any problem, "cd test" and run "newt install". At this point I get following error message: "Error: Error downloading repository apache-mynewt-core: No remote upstream for branch "master"". Any hints on how to solve that would be quite appreciated!

Some logs are attached.

```
OTLabs@Workstation MSYS ~
$ newt version
Apache Newt version: 1.5.0

OTLabs@Workstation MSYS ~
$ cd temp/

OTLabs@Workstation MSYS ~/temp
$ newt new test
Downloading project skeleton from apache/mynewt-blinky...
Downloading repository mynewt-blinky (commit: mynewt_1_5_0_tag) from https://github.com/apache/mynewt-blinky.git
Installing skeleton in test...
Project test successfully created.

OTLabs@Workstation MSYS ~/temp
$ cd test/

OTLabs@Workstation MSYS ~/temp/test
$ newt install -v
[apache-mynewt-core]:
Downloading repository description
Downloading repository mynewt-core (commit: master) from https://github.com/apache/mynewt-core.git
Cloning into '/tmp/newt-repo409220155'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 99130 (delta 10), reused 15 (delta 6), pack-reused 99101
Receiving objects: 100% (99130/99130), 155.65 MiB | 3.29 MiB/s, done.
Resolving deltas: 100% (60414/60414), done.
Checking out files: 100% (5524/5524), done.
Error: Error downloading repository apache-mynewt-core: No remote upstream for branch "master"
```

**Comment by utzig** [comment]
Would you mind attaching the output of `newt -ldebug install -v`?

**Comment by OTLabs** [comment]
With pleasure, here it goes:

```
$ newt -ldebug install -v
2018/12/26 09:13:03.790 [DEBUG] Searching for project file C:/msys64/home/otlabs/tmp/test20181226/project.yml
2018/12/26 09:13:03.915 [DEBUG] Failed to read C:\Users\otlabs/.newt/repos.yml file
2018/12/26 09:13:03.918 [DEBUG] Loading configuration for package C:/msys64/home/otlabs/tmp/test20181226/apps/blinky
2018/12/26 09:13:03.919 [DEBUG] Loading configuration for package C:/msys64/home/otlabs/tmp/test20181226/targets/my_blinky_sim
2018/12/26 09:13:03.919 [DEBUG] Loading configuration for package C:/msys64/home/otlabs/tmp/test20181226/targets/unittest
[apache-mynewt-core]:
Downloading repository description
Downloading repository mynewt-core (commit: master) from https://github.com/apache/mynewt-core.git
2018/12/26 09:13:03.921 [INFO] [VERBOSE] C:/msys64/usr/bin/git.exe
Cloning into '/tmp/newt-repo412596267'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 99130 (delta 10), reused 15 (delta 6), pack-reused 99101
Receiving objects: 100% (99130/99130), 155.65 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (60414/60414), done.
Checking out files: 100% (5524/5524), done.
2018/12/26 09:14:56.032 [DEBUG] C:/msys64/usr/bin/git.exe merge-base master master
2018/12/26 09:14:56.229 [DEBUG] o=cf4cf8c42275a39e7b4a58803efd44740d0d6d07

2018/12/26 09:14:56.229 [DEBUG] C:/msys64/usr/bin/git.exe show-ref --verify --quiet refs/heads/master
2018/12/26 09:14:56.411 [DEBUG] o=
2018/12/26 09:14:56.411 [DEBUG] C:/msys64/usr/bin/git.exe merge-base master master
2018/12/26 09:14:56.543 [DEBUG] o=cf4cf8c42275a39e7b4a58803efd44740d0d6d07

2018/12/26 09:14:56.543 [DEBUG] C:/msys64/usr/bin/git.exe show-ref --verify --quiet refs/heads/master
2018/12/26 09:14:56.668 [DEBUG] o=
2018/12/26 09:14:56.668 [DEBUG] C:/msys64/usr/bin/git.exe rev-parse --abbrev-ref --symbolic-full-name master@{u}
2018/12/26 09:14:56.786 [DEBUG] o=fatal: ambiguous argument 'master@u': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
master@u

2018/12/26 09:14:56.995 [DEBUG] err=exit status 128
2018/12/26 09:15:00.545 [DEBUG] goroutine 1 [running]:
mynewt.apache.org/newt/util.NewNewtError(0xc0422ed2c0, 0x57, 0xc0420778c0)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/util/util.go:75 +0xef
mynewt.apache.org/newt/util.FmtNewtError(0x7bb067, 0x23, 0xc0420778c0, 0x2, 0x2, 0x7f5b20)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/util/util.go:82 +0x72
mynewt.apache.org/newt/newt/repo.(*Repo).downloadRepo(0xc0420e4d90, 0x7aa951, 0x6, 0x0, 0x0)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/repo/repo.go:208 +0x2b8
mynewt.apache.org/newt/newt/repo.(*Repo).ensureExists(0xc0420e4d90, 0x7c8d40, 0xc042077980)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/repo/repo.go:359 +0xc0
mynewt.apache.org/newt/newt/repo.(*Repo).downloadFile(0xc0420e4d90, 0x7aa951, 0x6, 0x7af793, 0xe, 0x0, 0xc0421e80c0, 0x7f5c60, 0xc0421e8090)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/repo/repo.go:378 +0x5c
mynewt.apache.org/newt/newt/repo.(*Repo).downloadRepositoryYml(0xc0420e4d90, 0x4b, 0x1ed)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/repo/repo.go:401 +0x5c
mynewt.apache.org/newt/newt/repo.(*Repo).DownloadDesc(0xc0420e4d90, 0x7aa393, 0x6)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/repo/repo.go:427 +0xac
mynewt.apache.org/newt/newt/repo.(*Repo).UpdateDesc(0xc0420e4d90, 0xc04204f510, 0x2, 0x2)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/repo/repo.go:342 +0xcc
mynewt.apache.org/newt/newt/project.(*Project).downloadRepositoryYmlFiles(0xc0420e4b60, 0x41034f, 0x10)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/project/project.go:464 +0x75
mynewt.apache.org/newt/newt/project.(*Project).InstallIf(0xc0420e4b60, 0x0, 0xc04204f500, 0xc04204f500, 0x0)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/project/project.go:266 +0x36
mynewt.apache.org/newt/newt/cli.installRunCmd(0xc042127400, 0xc042002b80, 0x0, 0x2)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/cli/project_cmds.go:110 +0xae
mynewt.apache.org/newt/vendor/github.com/spf13/cobra.(*Command).execute(0xc042127400, 0xc042002ae0, 0x2, 0x2, 0xc042127400, 0xc042002ae0)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/vendor/github.com/spf13/cobra/command.go:766 +0x2c8
mynewt.apache.org/newt/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042078a00, 0xffffffffffffffff, 0x4, 0x7a9255)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/vendor/github.com/spf13/cobra/command.go:852 +0x311
mynewt.apache.org/newt/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042078a00, 0x7a9255, 0x4)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/vendor/github.com/spf13/cobra/command.go:800 +0x32
main.main()
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/newt/newt.go:170 +0x18e

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        C:/msys64/mingw64/lib/go/src/runtime/sigqueue.go:139 +0xad
os/signal.loop()
        C:/msys64/mingw64/lib/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
        C:/msys64/mingw64/lib/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [chan receive]:
mynewt.apache.org/newt/util.ShellInteractiveCommand.func1(0xc0421e5860)
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/util/util.go:358 +0x3b
created by mynewt.apache.org/newt/util.ShellInteractiveCommand
        C:/msys64/home/vbox/dev/go/src/mynewt.apache.org/newt/util/util.go:357 +0x1f0

Error: Error downloading repository apache-mynewt-core: No remote upstream for branch "master"

```

**Comment by sjanc** [comment]
Hi,

looks like indeed windows newt was broken..  PR with fix is pending review https://github.com/apache/mynewt-newt/pull/259 so this issue should be fixed in next release.

**Comment by sjanc** [comment]
Hi, 

Mynewt 1.6 was released so this should be fixed. Since we noticed some inconsistency among windows enviroments, we also decided to add an option to tune this.

By default on windows escaping is enabled but can be disabled with '--escape=false'  option eg  'newt --escape=false install -v'


Let me know if this works for you.

**Comment by OTLabs** [comment]
@sjanc It works like a charm now! Thank you!

Here is a log for basic project:
```
user@workstation MSYS ~
$ newt version
Apache Newt
   Version: 1.6.0
  Git Hash: da3758b
Build Date: 2019-04-02_22:49

user@workstation MSYS ~
$ cd tmp/

user@workstation MSYS ~/tmp
$ newt new test20190411
Downloading project skeleton from apache/mynewt-blinky...
Downloading repository mynewt-blinky (commit: mynewt_1_6_0_tag) from https://github.com/apache/mynewt-blinky.git
Installing skeleton in test20190411...
Project test20190411 successfully created.

user@workstation MSYS ~/tmp
$ cd test20190411/

user@workstation MSYS ~/tmp/test20190411
$ ls
apps  LICENSE  NOTICE  project.yml  README.md  targets

user@workstation MSYS ~/tmp/test20190411
$ newt install
Downloading repository mynewt-core (commit: master) from https://github.com/apache/mynewt-core.git
Downloading repository mynewt-nimble (commit: master) from https://github.com/apache/mynewt-nimble.git
Making the following changes to the project:
    install apache-mynewt-core (1.6.0)
    install apache-mynewt-nimble (1.1.0)
apache-mynewt-core successfully installed version 1.6.0
apache-mynewt-nimble successfully installed version 1.1.0
```
I use git from msys2.

**Comment by sjanc** [comment]
great, thanks for confirmation

**Comment by tcpipchip** [comment]
yes, dont use the windows GIT

**Comment by tcpipchip** [comment]
use a installed GIT installed o msys
